import Head from "next/head";
import { Box } from "@chakra-ui/react";
import { Inter } from "@next/font/google";
import Header from "../components/Header";
import Features from "../components/Home/Features";
import Navbar from "../components/Navbar";
import Price from "../components/Pricing";

import Chat from "../components/chat"
import Footer from "../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Ray a learning app for all aspiring web developers and Students
          willing to upload their own videos
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Chat/>
      <Box>
        <Navbar />
        <Header />
        <Features />
        <Price />
        <Footer />
      </Box>
    </>
  );
}
