import Head from 'next/head'
import { Box } from "@chakra-ui/react";
import { Inter } from '@next/font/google'

import Navbar from "../components/Navbar";
import Pricing from "../components/Pricing";

import Footer from "../components/Footer";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
      <Navbar />
      <Pricing />
      <Footer />
      </Box>
    </>
  )
}
