export const GETCOURSE_REQUEST = "GETCOURSE_REQUEST";
export const GETCOURSE_SUCCESS = "GETCOURSE_SUCCESS";
export const GETCOURSE_FAILURE = "GETCOURSE_FAILURE";
export const GETSINGLECOURSE_REQUEST = "GETSINGLECOURSE_REQUEST";
export const GETSINGLECOURSE_SUCCESS = "GETSINGLECOURSE_SUCCESS";
export const GETSINGLECOURSE_FAILURE = "GETSINGLECOURSE_FAILURE";
